#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

#include <stdio.h>     
#include <stdlib.h>
#include <cstring>
#include <iostream>
#include <string>
#include "myscanner.h"

using namespace std;


// stuff from flex that bison needs to know about:
extern "C" int yylex();
extern "C" int yyparse();
extern "C" int YYRECOVERING();
extern "C" FILE *yyin;
extern "C" FILE *yytext;
extern int line_num;
char found[10000];
char needed[10000];

#line 26 "parser.y"
typedef union 
{
    int numi;
    float numf;
    char *str;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	ERRODESC	258
#define	IDENT	259
#define	SEMICOLON	260
#define	ENDPOINT	261
#define	ATTRIBUTION	262
#define	CONST_IDENT	263
#define	COLON	264
#define	TYPE	265
#define	COMMA	266
#define	PROCEDURE_IDENT	267
#define	OPEN_PAR	268
#define	CLOSE_PAR	269
#define	EQUAL	270
#define	DIF	271
#define	GREATER_EQUAL	272
#define	LESSER_EQUAL	273
#define	GREATER	274
#define	LESSER	275
#define	PLUS	276
#define	MINUS	277
#define	MULT	278
#define	DIV	279
#define	INTEGER_NUMBER	280
#define	REAL_NUMBER	281
#define	UNEXPECTED_CHAR	282
#define	ERROINT	283
#define	ERROIDENT	284
#define	ERROFLOAT	285
#define	ERROTAM	286
#define	PROGRAM	287
#define	BEG	288
#define	END	289
#define	IF	290
#define	ELSE	291
#define	CONST	292
#define	VAR	293
#define	PROCEDURE	294
#define	REAL	295
#define	INTEGER	296
#define	READ	297
#define	WRITE	298
#define	WHILE	299
#define	DO	300
#define	THEN	301
#define	FOR	302
#define	TO	303


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int ERRODESC;
static const int IDENT;
static const int SEMICOLON;
static const int ENDPOINT;
static const int ATTRIBUTION;
static const int CONST_IDENT;
static const int COLON;
static const int TYPE;
static const int COMMA;
static const int PROCEDURE_IDENT;
static const int OPEN_PAR;
static const int CLOSE_PAR;
static const int EQUAL;
static const int DIF;
static const int GREATER_EQUAL;
static const int LESSER_EQUAL;
static const int GREATER;
static const int LESSER;
static const int PLUS;
static const int MINUS;
static const int MULT;
static const int DIV;
static const int INTEGER_NUMBER;
static const int REAL_NUMBER;
static const int UNEXPECTED_CHAR;
static const int ERROINT;
static const int ERROIDENT;
static const int ERROFLOAT;
static const int ERROTAM;
static const int PROGRAM;
static const int BEG;
static const int END;
static const int IF;
static const int ELSE;
static const int CONST;
static const int VAR;
static const int PROCEDURE;
static const int REAL;
static const int INTEGER;
static const int READ;
static const int WRITE;
static const int WHILE;
static const int DO;
static const int THEN;
static const int FOR;
static const int TO;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,ERRODESC=258
	,IDENT=259
	,SEMICOLON=260
	,ENDPOINT=261
	,ATTRIBUTION=262
	,CONST_IDENT=263
	,COLON=264
	,TYPE=265
	,COMMA=266
	,PROCEDURE_IDENT=267
	,OPEN_PAR=268
	,CLOSE_PAR=269
	,EQUAL=270
	,DIF=271
	,GREATER_EQUAL=272
	,LESSER_EQUAL=273
	,GREATER=274
	,LESSER=275
	,PLUS=276
	,MINUS=277
	,MULT=278
	,DIV=279
	,INTEGER_NUMBER=280
	,REAL_NUMBER=281
	,UNEXPECTED_CHAR=282
	,ERROINT=283
	,ERROIDENT=284
	,ERROFLOAT=285
	,ERROTAM=286
	,PROGRAM=287
	,BEG=288
	,END=289
	,IF=290
	,ELSE=291
	,CONST=292
	,VAR=293
	,PROCEDURE=294
	,REAL=295
	,INTEGER=296
	,READ=297
	,WRITE=298
	,WHILE=299
	,DO=300
	,THEN=301
	,FOR=302
	,TO=303


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::ERRODESC=258;
const int YY_parse_CLASS::IDENT=259;
const int YY_parse_CLASS::SEMICOLON=260;
const int YY_parse_CLASS::ENDPOINT=261;
const int YY_parse_CLASS::ATTRIBUTION=262;
const int YY_parse_CLASS::CONST_IDENT=263;
const int YY_parse_CLASS::COLON=264;
const int YY_parse_CLASS::TYPE=265;
const int YY_parse_CLASS::COMMA=266;
const int YY_parse_CLASS::PROCEDURE_IDENT=267;
const int YY_parse_CLASS::OPEN_PAR=268;
const int YY_parse_CLASS::CLOSE_PAR=269;
const int YY_parse_CLASS::EQUAL=270;
const int YY_parse_CLASS::DIF=271;
const int YY_parse_CLASS::GREATER_EQUAL=272;
const int YY_parse_CLASS::LESSER_EQUAL=273;
const int YY_parse_CLASS::GREATER=274;
const int YY_parse_CLASS::LESSER=275;
const int YY_parse_CLASS::PLUS=276;
const int YY_parse_CLASS::MINUS=277;
const int YY_parse_CLASS::MULT=278;
const int YY_parse_CLASS::DIV=279;
const int YY_parse_CLASS::INTEGER_NUMBER=280;
const int YY_parse_CLASS::REAL_NUMBER=281;
const int YY_parse_CLASS::UNEXPECTED_CHAR=282;
const int YY_parse_CLASS::ERROINT=283;
const int YY_parse_CLASS::ERROIDENT=284;
const int YY_parse_CLASS::ERROFLOAT=285;
const int YY_parse_CLASS::ERROTAM=286;
const int YY_parse_CLASS::PROGRAM=287;
const int YY_parse_CLASS::BEG=288;
const int YY_parse_CLASS::END=289;
const int YY_parse_CLASS::IF=290;
const int YY_parse_CLASS::ELSE=291;
const int YY_parse_CLASS::CONST=292;
const int YY_parse_CLASS::VAR=293;
const int YY_parse_CLASS::PROCEDURE=294;
const int YY_parse_CLASS::REAL=295;
const int YY_parse_CLASS::INTEGER=296;
const int YY_parse_CLASS::READ=297;
const int YY_parse_CLASS::WRITE=298;
const int YY_parse_CLASS::WHILE=299;
const int YY_parse_CLASS::DO=300;
const int YY_parse_CLASS::THEN=301;
const int YY_parse_CLASS::FOR=302;
const int YY_parse_CLASS::TO=303;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		179
#define	YYFLAG		-32768
#define	YYNTBASE	50

#define YYTRANSLATE(x) ((unsigned)(x) <= 303 ? yytranslate[x] : 81)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    49,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     6,    11,    14,    17,    22,    27,    30,    34,    41,
    47,    51,    52,    59,    65,    69,    70,    72,    74,    77,
    80,    81,    88,    93,    94,    98,    99,   104,   109,   112,
   113,   119,   125,   128,   130,   134,   135,   138,   141,   142,
   145,   146,   150,   151,   156,   161,   168,   174,   178,   181,
   185,   196,   201,   204,   208,   210,   212,   214,   216,   218,
   220,   221,   224,   226,   228,   229,   233,   234,   236,   238,
   242,   246,   247,   249,   251,   253,   255,   259,   261
};

static const short yyrhs[] = {    32,
     4,     5,    51,     6,     0,     1,     5,    51,     6,     0,
     1,     6,     0,     1,    49,     0,    52,    33,    68,    34,
     0,     1,    33,    68,    34,     0,     1,    34,     0,    53,
    54,    58,     0,    37,     4,    15,    80,     5,    53,     0,
     1,    15,    80,     5,    53,     0,     1,     5,    53,     0,
     0,    38,    56,     9,    55,     5,    54,     0,     1,     9,
    55,     5,    54,     0,     1,     5,    54,     0,     0,    40,
     0,    41,     0,     4,    57,     0,    11,    56,     0,     0,
    39,     4,    59,     5,    62,    58,     0,     1,     5,    62,
    58,     0,     0,    13,    60,    14,     0,     0,    56,     9,
    55,    61,     0,     1,     9,    55,    61,     0,     5,    60,
     0,     0,    63,    33,    68,    34,     5,     0,     1,    33,
    68,    34,     5,     0,     1,     5,     0,    54,     0,    13,
    65,    14,     0,     0,     4,    66,     0,     5,    65,     0,
     0,    36,    69,     0,     0,    69,     5,    68,     0,     0,
    42,    13,    56,    14,     0,    43,    13,    56,    14,     0,
    44,    13,    70,    14,    45,    69,     0,    35,    70,    46,
    69,    67,     0,     4,     7,    72,     0,     4,    64,     0,
    33,    68,    34,     0,    47,     4,     7,    80,    48,    80,
    45,    33,    68,    34,     0,     1,    46,    69,    67,     0,
     1,    34,     0,    72,    71,    72,     0,    15,     0,    16,
     0,    17,     0,    18,     0,    19,     0,    20,     0,     0,
    76,    74,     0,    21,     0,    22,     0,     0,    75,    76,
    74,     0,     0,    21,     0,    22,     0,    73,    79,    77,
     0,    78,    79,    77,     0,     0,    23,     0,    24,     0,
     4,     0,    80,     0,    13,    72,    14,     0,    25,     0,
    26,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    92,    93,    94,    95,    97,    98,    99,   101,   103,   104,
   105,   106,   108,   109,   110,   111,   113,   114,   116,   118,
   119,   121,   122,   123,   125,   126,   128,   129,   131,   132,
   134,   135,   136,   138,   140,   141,   143,   144,   145,   147,
   148,   150,   151,   153,   154,   155,   156,   157,   158,   159,
   160,   161,   162,   164,   166,   167,   168,   169,   170,   171,
   172,   174,   176,   177,   178,   180,   181,   183,   184,   186,
   188,   189,   191,   192,   194,   195,   196,   198,   199
};

static const char * const yytname[] = {   "$","error","$illegal.","ERRODESC",
"IDENT","SEMICOLON","ENDPOINT","ATTRIBUTION","CONST_IDENT","COLON","TYPE","COMMA",
"PROCEDURE_IDENT","OPEN_PAR","CLOSE_PAR","EQUAL","DIF","GREATER_EQUAL","LESSER_EQUAL",
"GREATER","LESSER","PLUS","MINUS","MULT","DIV","INTEGER_NUMBER","REAL_NUMBER",
"UNEXPECTED_CHAR","ERROINT","ERROIDENT","ERROFLOAT","ERROTAM","PROGRAM","BEG",
"END","IF","ELSE","CONST","VAR","PROCEDURE","REAL","INTEGER","READ","WRITE",
"WHILE","DO","THEN","FOR","TO","'\\n'","programa","corpo","dc","dc_c","dc_v",
"tipo_var","variaveis","mais_var","dc_p","parametros","lista_par","mais_par",
"corpo_p","dc_loc","lista_arg","argumentos","mais_ident","pfalsa","comandos",
"cmd","condicao","relacao","expressao","op_un","outros_termos","op_ad","termo",
"mais_fatores","op_mul","fator","numero",""
};
#endif

static const short yyr1[] = {     0,
    50,    50,    50,    50,    51,    51,    51,    52,    53,    53,
    53,    53,    54,    54,    54,    54,    55,    55,    56,    57,
    57,    58,    58,    58,    59,    59,    60,    60,    61,    61,
    62,    62,    62,    63,    64,    64,    65,    66,    66,    67,
    67,    68,    68,    69,    69,    69,    69,    69,    69,    69,
    69,    69,    69,    70,    71,    71,    71,    71,    71,    71,
    71,    72,    73,    73,    73,    74,    74,    75,    75,    76,
    77,    77,    78,    78,    79,    79,    79,    80,    80
};

static const short yyr2[] = {     0,
     5,     4,     2,     2,     4,     4,     2,     3,     6,     5,
     3,     0,     6,     5,     3,     0,     1,     1,     2,     2,
     0,     6,     4,     0,     3,     0,     4,     4,     2,     0,
     5,     5,     2,     1,     3,     0,     2,     2,     0,     2,
     0,     3,     0,     4,     4,     6,     5,     3,     2,     3,
    10,     4,     2,     3,     1,     1,     1,     1,     1,     1,
     0,     2,     1,     1,     0,     3,     0,     1,     1,     3,
     3,     0,     1,     1,     1,     1,     3,     1,     1
};

static const short yydefact[] = {     0,
     0,     0,     0,     3,     4,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     7,     0,     2,     0,     0,
     0,     0,     0,     0,    11,    78,    79,     0,     0,    36,
     0,    65,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    21,     0,     0,     0,     8,     1,     0,    53,
     0,    65,     0,    49,     0,    63,    64,     0,    61,     0,
    67,     0,     0,    65,     0,     6,     0,     0,     5,    15,
    17,    18,     0,     0,    19,     0,     0,    26,    10,    41,
    48,    39,     0,    50,     0,    55,    56,    57,    58,    59,
    60,    65,    75,    65,    72,    76,    68,    69,    62,    65,
     0,     0,     0,     0,    42,     0,     0,    20,     0,     0,
    34,     0,     0,     0,     0,     0,    52,     0,    37,    35,
    41,    54,     0,    73,    74,    70,     0,    67,    44,    45,
     0,     0,     9,    14,     0,     0,     0,    23,     0,     0,
     0,     0,     0,    40,    38,    47,    77,    72,    66,     0,
     0,    13,     0,     0,     0,     0,    25,     0,    71,    46,
     0,     0,     0,    30,    30,    22,     0,    32,    31,     0,
    28,    27,     0,    29,     0,    51,     0,     0,     0
};

static const short yydefgoto[] = {   177,
     9,    10,    11,    70,    73,   141,    75,    47,   115,   142,
   171,   112,   113,    54,    83,   119,   117,    37,    38,    58,
    92,    59,    60,    99,   100,    61,   126,   127,    95,    96
};

static const short yypact[] = {     5,
    11,    24,    39,-32768,-32768,    25,    56,    32,    35,    31,
    41,    39,    62,     9,    10,-32768,    73,-32768,    10,    20,
    90,    72,    91,    18,-32768,-32768,-32768,    97,   -26,     8,
    10,    60,   102,   106,   108,   100,    76,   101,     9,    88,
    41,    68,   113,   114,   120,   129,-32768,-32768,    62,-32768,
    23,    60,   131,-32768,   103,-32768,-32768,    94,   112,     6,
    92,    90,    90,    60,   132,-32768,    10,   136,-32768,-32768,
-32768,-32768,   137,    90,-32768,    68,    74,   123,-32768,   107,
-32768,   139,   133,-32768,    23,-32768,-32768,-32768,-32768,-32768,
-32768,    60,-32768,    60,    93,-32768,-32768,-32768,-32768,    60,
   134,   135,   138,     9,-32768,    62,    41,-32768,   140,    13,
-32768,    72,   117,    82,   141,    23,-32768,   131,-32768,-32768,
   107,-32768,   142,-32768,-32768,-32768,     6,    92,-32768,-32768,
   110,   105,-32768,-32768,    41,    54,    10,-32768,    10,   148,
   149,   145,    74,-32768,-32768,-32768,-32768,    93,-32768,    23,
     9,-32768,   126,   127,    68,    68,-32768,    72,-32768,-32768,
   118,   146,   157,   159,   159,-32768,   143,-32768,-32768,    82,
-32768,-32768,    10,-32768,   144,-32768,   165,   166,-32768
};

static const short yypgoto[] = {-32768,
   155,-32768,   -10,    -9,   -71,   -12,-32768,   -99,-32768,    -2,
     4,    27,-32768,-32768,    53,-32768,    51,   -19,   -47,   109,
-32768,   -45,-32768,    46,-32768,    75,    29,-32768,    52,   -13
};


#define	YYLAST		179


static const short yytable[] = {    40,
    28,    22,    25,    80,   109,     1,    81,    50,    44,    93,
    29,    55,   138,    30,    52,     3,     4,   136,    94,    51,
    53,    42,    13,    29,    41,    68,    30,     6,    42,    12,
    26,    27,    14,    26,    27,    17,     2,   121,    79,     7,
    18,    20,    31,   -43,    32,   137,   122,   105,   123,   101,
   102,    33,    34,    35,    20,    31,    36,    32,   166,     5,
    13,   108,    24,    19,    33,    34,    35,   111,   144,    36,
    14,   -12,    45,   -16,   110,     8,   -12,   -12,    21,   -16,
    56,    57,   140,   164,   165,    43,   -16,    39,    15,    16,
   132,    21,   -33,    43,   -12,   133,    48,   134,     8,   -12,
   -12,    49,   160,    65,   -24,    67,   -16,    71,    72,    66,
    46,    21,    97,    98,    62,   124,   125,   153,    63,   154,
    64,    69,    76,    74,    77,   152,    86,    87,    88,    89,
    90,    91,    78,   111,    82,   114,    84,   161,   104,    85,
   106,   107,   116,   118,   135,   143,   120,   129,   130,   139,
   168,   131,   151,   175,   150,   147,   155,   156,   157,   162,
   163,   169,   167,   170,   178,   179,    23,   174,   172,   158,
   145,   146,   103,   149,   128,   173,   159,   176,   148
};

static const short yycheck[] = {    19,
    14,    11,    13,    51,    76,     1,    52,    34,    21,     4,
     1,    31,   112,     4,     7,     5,     6,     5,    13,    46,
    13,     9,     5,     1,     5,    39,     4,     4,     9,     5,
    25,    26,    15,    25,    26,     4,    32,    85,    49,     1,
     6,     1,    33,    34,    35,    33,    92,    67,    94,    62,
    63,    42,    43,    44,     1,    33,    47,    35,   158,    49,
     5,    74,     1,    33,    42,    43,    44,    77,   116,    47,
    15,    33,     1,    33,     1,    37,    38,    39,    38,    39,
    21,    22,     1,   155,   156,     4,    33,    15,    33,    34,
   104,    38,    39,     4,    33,   106,     6,   107,    37,    38,
    39,     5,   150,     4,    33,     5,    33,    40,    41,    34,
    39,    38,    21,    22,    13,    23,    24,   137,    13,   139,
    13,    34,     9,    11,     5,   135,    15,    16,    17,    18,
    19,    20,     4,   143,     4,    13,    34,   151,     7,    46,
     5,     5,    36,     5,     5,     5,    14,    14,    14,    33,
     5,    14,    48,   173,    45,    14,     9,     9,    14,    34,
    34,     5,    45,     5,     0,     0,    12,   170,   165,   143,
   118,   121,    64,   128,   100,    33,   148,    34,   127
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 92 "parser.y"
{;;
    break;}
case 2:
#line 93 "parser.y"
{;;
    break;}
case 3:
#line 94 "parser.y"
{;;
    break;}
case 4:
#line 95 "parser.y"
{;;
    break;}
case 5:
#line 97 "parser.y"
{;;
    break;}
case 6:
#line 98 "parser.y"
{;;
    break;}
case 7:
#line 99 "parser.y"
{;;
    break;}
case 8:
#line 101 "parser.y"
{;;
    break;}
case 9:
#line 103 "parser.y"
{;;
    break;}
case 10:
#line 104 "parser.y"
{;;
    break;}
case 11:
#line 105 "parser.y"
{;;
    break;}
case 12:
#line 106 "parser.y"
{;;
    break;}
case 13:
#line 108 "parser.y"
{;;
    break;}
case 14:
#line 109 "parser.y"
{;;
    break;}
case 15:
#line 110 "parser.y"
{;;
    break;}
case 16:
#line 111 "parser.y"
{;;
    break;}
case 17:
#line 113 "parser.y"
{;;
    break;}
case 18:
#line 114 "parser.y"
{;;
    break;}
case 19:
#line 116 "parser.y"
{;;
    break;}
case 20:
#line 118 "parser.y"
{;;
    break;}
case 21:
#line 119 "parser.y"
{;;
    break;}
case 22:
#line 121 "parser.y"
{;;
    break;}
case 23:
#line 122 "parser.y"
{;;
    break;}
case 24:
#line 123 "parser.y"
{;;
    break;}
case 25:
#line 125 "parser.y"
{;;
    break;}
case 26:
#line 126 "parser.y"
{;;
    break;}
case 27:
#line 128 "parser.y"
{;;
    break;}
case 28:
#line 129 "parser.y"
{;;
    break;}
case 29:
#line 131 "parser.y"
{;;
    break;}
case 30:
#line 132 "parser.y"
{;;
    break;}
case 31:
#line 134 "parser.y"
{;;
    break;}
case 32:
#line 135 "parser.y"
{;;
    break;}
case 33:
#line 136 "parser.y"
{;;
    break;}
case 34:
#line 138 "parser.y"
{;;
    break;}
case 35:
#line 140 "parser.y"
{;;
    break;}
case 36:
#line 141 "parser.y"
{;;
    break;}
case 37:
#line 143 "parser.y"
{;;
    break;}
case 38:
#line 144 "parser.y"
{;;
    break;}
case 39:
#line 145 "parser.y"
{;;
    break;}
case 40:
#line 147 "parser.y"
{;;
    break;}
case 41:
#line 148 "parser.y"
{;;
    break;}
case 42:
#line 150 "parser.y"
{;;
    break;}
case 43:
#line 151 "parser.y"
{;;
    break;}
case 44:
#line 153 "parser.y"
{;;
    break;}
case 45:
#line 154 "parser.y"
{;;
    break;}
case 46:
#line 155 "parser.y"
{;;
    break;}
case 47:
#line 156 "parser.y"
{;;
    break;}
case 48:
#line 157 "parser.y"
{;;
    break;}
case 49:
#line 158 "parser.y"
{;;
    break;}
case 50:
#line 159 "parser.y"
{;;
    break;}
case 51:
#line 160 "parser.y"
{;;
    break;}
case 52:
#line 161 "parser.y"
{;;
    break;}
case 53:
#line 162 "parser.y"
{;;
    break;}
case 54:
#line 164 "parser.y"
{;;
    break;}
case 55:
#line 166 "parser.y"
{;;
    break;}
case 56:
#line 167 "parser.y"
{;;
    break;}
case 57:
#line 168 "parser.y"
{;;
    break;}
case 58:
#line 169 "parser.y"
{;;
    break;}
case 59:
#line 170 "parser.y"
{;;
    break;}
case 60:
#line 171 "parser.y"
{;;
    break;}
case 61:
#line 172 "parser.y"
{;;
    break;}
case 62:
#line 174 "parser.y"
{;;
    break;}
case 63:
#line 176 "parser.y"
{;;
    break;}
case 64:
#line 177 "parser.y"
{;;
    break;}
case 65:
#line 178 "parser.y"
{;;
    break;}
case 66:
#line 180 "parser.y"
{;;
    break;}
case 67:
#line 181 "parser.y"
{;;
    break;}
case 68:
#line 183 "parser.y"
{;;
    break;}
case 69:
#line 184 "parser.y"
{;;
    break;}
case 70:
#line 186 "parser.y"
{;;
    break;}
case 71:
#line 188 "parser.y"
{;;
    break;}
case 72:
#line 189 "parser.y"
{;;
    break;}
case 73:
#line 191 "parser.y"
{;;
    break;}
case 74:
#line 192 "parser.y"
{;;
    break;}
case 75:
#line 194 "parser.y"
{;;
    break;}
case 76:
#line 195 "parser.y"
{;;
    break;}
case 77:
#line 196 "parser.y"
{;;
    break;}
case 78:
#line 198 "parser.y"
{;;
    break;}
case 79:
#line 199 "parser.y"
{;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
<<<<<<< HEAD
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
=======
        case 2:
#line 86 "parser.y" /* yacc.c:1646  */
    {sprintf(found, "%s %s %s %s\n", (yyvsp[-4].str), (yyvsp[-3].str), (yyvsp[-2].str), (yyvsp[0].str)); yyerror(found);}
#line 1508 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 3:
#line 87 "parser.y" /* yacc.c:1646  */
    {;}
#line 1514 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 4:
#line 88 "parser.y" /* yacc.c:1646  */
    {;}
#line 1520 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 5:
#line 89 "parser.y" /* yacc.c:1646  */
    {;}
#line 1526 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 6:
#line 91 "parser.y" /* yacc.c:1646  */
    {;}
#line 1532 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 7:
#line 92 "parser.y" /* yacc.c:1646  */
    {;}
#line 1538 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 8:
#line 93 "parser.y" /* yacc.c:1646  */
    {;}
#line 1544 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 9:
#line 95 "parser.y" /* yacc.c:1646  */
    {;}
#line 1550 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 10:
#line 97 "parser.y" /* yacc.c:1646  */
    {;}
#line 1556 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 11:
#line 98 "parser.y" /* yacc.c:1646  */
    {;}
#line 1562 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 12:
#line 99 "parser.y" /* yacc.c:1646  */
    {;}
#line 1568 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 13:
#line 100 "parser.y" /* yacc.c:1646  */
    {;}
#line 1574 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 14:
#line 102 "parser.y" /* yacc.c:1646  */
    {;}
#line 1580 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 15:
#line 103 "parser.y" /* yacc.c:1646  */
    {;}
#line 1586 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 16:
#line 104 "parser.y" /* yacc.c:1646  */
    {;}
#line 1592 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 17:
#line 105 "parser.y" /* yacc.c:1646  */
    {;}
#line 1598 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 18:
#line 107 "parser.y" /* yacc.c:1646  */
    {;}
#line 1604 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 19:
#line 108 "parser.y" /* yacc.c:1646  */
    {;}
#line 1610 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 20:
#line 110 "parser.y" /* yacc.c:1646  */
    {;}
#line 1616 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 21:
#line 112 "parser.y" /* yacc.c:1646  */
    {;}
#line 1622 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 22:
#line 113 "parser.y" /* yacc.c:1646  */
    {;}
#line 1628 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 23:
#line 115 "parser.y" /* yacc.c:1646  */
    {;}
#line 1634 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 24:
#line 116 "parser.y" /* yacc.c:1646  */
    {;}
#line 1640 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 25:
#line 117 "parser.y" /* yacc.c:1646  */
    {;}
#line 1646 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 26:
#line 119 "parser.y" /* yacc.c:1646  */
    {;}
#line 1652 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 27:
#line 120 "parser.y" /* yacc.c:1646  */
    {;}
#line 1658 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 28:
#line 122 "parser.y" /* yacc.c:1646  */
    {;}
#line 1664 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 29:
#line 123 "parser.y" /* yacc.c:1646  */
    {;}
#line 1670 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 30:
#line 125 "parser.y" /* yacc.c:1646  */
    {;}
#line 1676 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 31:
#line 126 "parser.y" /* yacc.c:1646  */
    {;}
#line 1682 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 32:
#line 128 "parser.y" /* yacc.c:1646  */
    {;}
#line 1688 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 33:
#line 129 "parser.y" /* yacc.c:1646  */
    {;}
#line 1694 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 34:
#line 130 "parser.y" /* yacc.c:1646  */
    {;}
#line 1700 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 35:
#line 132 "parser.y" /* yacc.c:1646  */
    {;}
#line 1706 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 36:
#line 134 "parser.y" /* yacc.c:1646  */
    {;}
#line 1712 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 37:
#line 135 "parser.y" /* yacc.c:1646  */
    {;}
#line 1718 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 38:
#line 137 "parser.y" /* yacc.c:1646  */
    {;}
#line 1724 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 39:
#line 138 "parser.y" /* yacc.c:1646  */
    {;}
#line 1730 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 40:
#line 139 "parser.y" /* yacc.c:1646  */
    {;}
#line 1736 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 41:
#line 141 "parser.y" /* yacc.c:1646  */
    {;}
#line 1742 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 42:
#line 142 "parser.y" /* yacc.c:1646  */
    {;}
#line 1748 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 43:
#line 144 "parser.y" /* yacc.c:1646  */
    {;}
#line 1754 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 44:
#line 145 "parser.y" /* yacc.c:1646  */
    {;}
#line 1760 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 45:
#line 147 "parser.y" /* yacc.c:1646  */
    {;}
#line 1766 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 46:
#line 148 "parser.y" /* yacc.c:1646  */
    {;}
#line 1772 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 47:
#line 149 "parser.y" /* yacc.c:1646  */
    {;}
#line 1778 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 48:
#line 150 "parser.y" /* yacc.c:1646  */
    {;}
#line 1784 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 49:
#line 151 "parser.y" /* yacc.c:1646  */
    {;}
#line 1790 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 50:
#line 152 "parser.y" /* yacc.c:1646  */
    {;}
#line 1796 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 51:
#line 153 "parser.y" /* yacc.c:1646  */
    {;}
#line 1802 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 52:
#line 154 "parser.y" /* yacc.c:1646  */
    {;}
#line 1808 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 53:
#line 155 "parser.y" /* yacc.c:1646  */
    {;}
#line 1814 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 54:
#line 156 "parser.y" /* yacc.c:1646  */
    {;}
#line 1820 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 55:
#line 158 "parser.y" /* yacc.c:1646  */
    {;}
#line 1826 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 56:
#line 160 "parser.y" /* yacc.c:1646  */
    {;}
#line 1832 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 57:
#line 161 "parser.y" /* yacc.c:1646  */
    {;}
#line 1838 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 58:
#line 162 "parser.y" /* yacc.c:1646  */
    {;}
#line 1844 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 59:
#line 163 "parser.y" /* yacc.c:1646  */
    {;}
#line 1850 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 60:
#line 164 "parser.y" /* yacc.c:1646  */
    {;}
#line 1856 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 61:
#line 165 "parser.y" /* yacc.c:1646  */
    {;}
#line 1862 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 62:
#line 166 "parser.y" /* yacc.c:1646  */
    {;}
#line 1868 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 63:
#line 168 "parser.y" /* yacc.c:1646  */
    {;}
#line 1874 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 64:
#line 170 "parser.y" /* yacc.c:1646  */
    {;}
#line 1880 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 65:
#line 171 "parser.y" /* yacc.c:1646  */
    {;}
#line 1886 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 66:
#line 172 "parser.y" /* yacc.c:1646  */
    {;}
#line 1892 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 67:
#line 174 "parser.y" /* yacc.c:1646  */
    {;}
#line 1898 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 68:
#line 175 "parser.y" /* yacc.c:1646  */
    {;}
#line 1904 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 69:
#line 177 "parser.y" /* yacc.c:1646  */
    {;}
#line 1910 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 70:
#line 178 "parser.y" /* yacc.c:1646  */
    {;}
#line 1916 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 71:
#line 180 "parser.y" /* yacc.c:1646  */
    {;}
#line 1922 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 72:
#line 182 "parser.y" /* yacc.c:1646  */
    {;}
#line 1928 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 73:
#line 183 "parser.y" /* yacc.c:1646  */
    {;}
#line 1934 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 74:
#line 185 "parser.y" /* yacc.c:1646  */
    {;}
#line 1940 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 75:
#line 186 "parser.y" /* yacc.c:1646  */
    {;}
#line 1946 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 76:
#line 188 "parser.y" /* yacc.c:1646  */
    {;}
#line 1952 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 77:
#line 189 "parser.y" /* yacc.c:1646  */
    {;}
#line 1958 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 78:
#line 190 "parser.y" /* yacc.c:1646  */
    {;}
#line 1964 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 79:
#line 192 "parser.y" /* yacc.c:1646  */
    {;}
#line 1970 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 80:
#line 193 "parser.y" /* yacc.c:1646  */
    {;}
#line 1976 "parser.tab.c" /* yacc.c:1646  */
    break;


#line 1980 "parser.tab.c" /* yacc.c:1646  */
      default: break;
>>>>>>> 87faca6f239ced5d0f86ac1c6da5355585bc69fe
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 205 "parser.y"


/**/

int main(int argc, char const *argv[]){
    int ntoken;
    int tam;
    return yyparse ( );
}
void yyerror(const char *str)
{
    if (!strcmp(yylval.str, "skip"))
    {
        yylval.str = strdup("");
        return;
    }
    printf("%s", str);
}
